name: CI/CD codERROR

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  IMAGE_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}/coderror

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, courses-service, progress-service]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ${{ matrix.service }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: pytest -q

  build-and-push:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push auth-service
        uses: docker/build-push-action@v6
        with:
          context: ./auth-service
          file: ./auth-service/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-auth-service:latest

      - name: Build and push courses-service
        uses: docker/build-push-action@v6
        with:
          context: ./courses-service
          file: ./courses-service/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-courses-service:latest

      - name: Build and push progress-service
        uses: docker/build-push-action@v6
        with:
          context: ./progress-service
          file: ./progress-service/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-progress-service:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    env:
      IMAGE_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}/coderror
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub on swarm node
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull latest images
        run: |
          docker pull $IMAGE_PREFIX-auth-service:latest
          docker pull $IMAGE_PREFIX-courses-service:latest
          docker pull $IMAGE_PREFIX-progress-service:latest
          docker pull $IMAGE_PREFIX-frontend:latest

      - name: Deploy stack to Swarm
        run: |
          docker stack deploy -c deploy/docker-stack.yml coderror
